### ISSUE TITLE
swap PIL dependency for Pillow

### ISSUE THREAD

**Issue by christopherlovell** [SKIRT/PTS9#3]
**Description**
`PIL` is incompatible with modern versions of other python packages, e.g. numpy, pandas, astropy, cython, scipy and h5py.

**Alternatives**
[Pillow](https://pillow.readthedocs.io/en/stable/index.html) is a 'friendly PIL fork', regularly updated, and (mostly) compatible with PIL.

**Context**
Happy to implement `Pillow` and test, but wanted to check there were no other reasons for choosing the original PIL distribution?

**Comment by petercamps** [comment]
Thanks for your inquiry and suggestion. For the avoidance of doubt, I assume we're talking about PTS 9 (this repo), not about the older PTS (other repo).

On my desktop I have an Anaconda Python 3.7 distribution with pillow 5.4.1 installed (not PIL). Still, apparently the import statement must still be "import PIL" because "import pillow" does not work. Confusing, I admit. Is your experience different?

**Comment by christopherlovell** [comment]
Yeah I'm looking at PTS 9. So it looks like pillow is actually imported as 

    from PIL import image

...identical to PIL. So nothing actually needs to be changed (see [here](https://pillow.readthedocs.io/en/stable/handbook/tutorial.html)). Hence why your distribution still works. I just assumed it would have a different import statement.

I also just noticed that the [documented requirements](http://www.skirt.ugent.be/pts9/_install_packages.html) explicitly state pillow, so apologies for wasting your time! I hit a dependency error when running PTS9 for the first time that requested PIL be installed, hence the issue above.
